### ISSUE TITLE
Code missing in ConfirmDontLoseMessages

### ISSUE THREAD

**Issue by powder366** [rabbitmq/rabbitmq-perf-test#19]
As described in
http://www.rabbitmq.com/blog/2011/02/10/introducing-publisher-confirms
The code related to
volatile SortedSet<Long> unconfirmedSet = Collections.synchronizedSortedSet(new TreeSet());
is missing. Could you add it?

**Comment by michaelklishin** [comment]
PerfTest has historically been a part of the examples package in RabbitMQ Java client. It has since evolved into a separate tool and was extracted but we keep dragging those examples along.

You are referring to a blog post from 2011 and the example today uses `waitForConfirmsOrDie`, which is the least efficient but also the easiest to understand (and handle failures with) API alternative may might or may not had been around in 2011. So this version has its own pros and cons but as an example, it is perfectly valid.

The right thing to do is to move these examples into a separate repo or delete them entirely, since there is no shortage of examples in doc guides, test suites and elsewhere on the Web.

**Comment by powder366** [comment]
I see. I think it was a good blog post. Keep the source and maybe add a hint in the blog post or provide both code examples. Thanks for answer.
