### ISSUE TITLE
how to set the ack ?

### ISSUE THREAD

**Issue by doubinyang** [rabbitmq/rabbitmq-perf-test#20]
run the rabbitmq-perf-test, want to set ack for the message?
look the image?
![image](https://cloud.githubusercontent.com/assets/3013733/23996597/edb613d6-0a88-11e7-8e2e-42b4f79e84be.png)

thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.
