### ISSUE TITLE
about consumer latency

### ISSUE THREAD

**Issue by didi20gh** [rabbitmq/rabbitmq-perf-test#233]
print msg :
id: test-030739-419, time: 420.052s, sent: 2102 msg/s, received: 10863 msg/s, min/median/75th/95th/99th consumer latency: 8141676/8715782/8769170/8826041/8833042 ?s
Q1 :
"?s" .  s for second or ms? :)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
