### ISSUE TITLE
test performance of mirror queue

### ISSUE THREAD

**Issue by jasonwangnanjing** [rabbitmq/rabbitmq-perf-test#243]
Hi Experts,
I want to test performance of mirror queue which defined within the cluster.But i did not find any suitable parameter from belog link.
https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#introduction
May you know any possibility to do it? if not, could we require this as feature?

BR Jason

**Comment by jasonwangnanjing** [comment]
--predeclared should be used.

**Comment by jasonwangnanjing** [comment]
--predeclared could be used to use defined mirror queue

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
