### ISSUE TITLE
set consumerTag from parameter

### ISSUE THREAD

**Issue by huzilin** [rabbitmq/rabbitmq-perf-test#246]
We need to pass consumerTag to server. Please add a consumerTag parameter. 

Thx

**Comment by michaelklishin** [comment]
And why do you need to do that? Consumer tags are only used for canceling consumers, which is not particularly important in the context of PerfTest runs.

We'd like to see more requests for this before we act on it. That said, this is open source software, so if you really need something, you can contribute it instead of asking others to do it.
