### ISSUE TITLE
No ack sent with -R 1

### ISSUE THREAD

**Issue by lhoguin** [rabbitmq/rabbitmq-perf-test#404]
The following command works fine and acks get sent regularly:

```
-x1 -y1 -c 10000 -s 12 -r 10 -A 10 -u cqv2 -qa x-queue-version=2
```

However adding `-R 1` results in acks not being sent. Wireshark only show C->S Basic.Publish, S->C Basic.Ack (confirm) and then S->C Basic.Deliver. The queue accumulates the pending acks as can be seen via the `rabbitmq_queue_message_unacked` for example.

It seems that also adding `-q 1` helps so that's probably related. But it would be good for `-R 1` to send acks once in a while especially when rates are this low.

**Comment by acogoluegnes** [comment]
I tried `-x1 -y1 -c 10000 -s 12 -r 10 -A 10 -u cqv2 -qa x-queue-version=2 -R 1` and I see a `basic.ack` from the client from time to time:

![image](https://user-images.githubusercontent.com/514737/194363232-61ce446a-74e3-4019-aacf-b041264577d6.png)

The default QoS is 0, so the broker will dispatch messages as soon as they arrive in the queue, so they will accumulate on the client side, which takes time to process them, that's why the number of un-acked messages grow.

Using e.g. `-q 20` avoids the problem of unack-ed messages but it's still difficult to see that messages are actually acked.

**Comment by lhoguin** [comment]
My bad! You're right. Just confirmed this as well.

**Comment by acogoluegnes** [comment]
With 10 msg / s inbound (so same rate for confirms), acking every 10 messages, but consuming 1 msg / s, it's a consumer `basic.ack` every 10 seconds in the middle of 100 confirms, so it can be difficult to find!
