### ISSUE TITLE
JAVA_OPTS doesn't work the way that the docs indicate

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-perf-test#416]
https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#tls-support

It took me a while to figure out why the above wasn't working. `JAVA_OPTS` is _not_ understood by the JVM, but it is up to the application to read the env variable and do something with it.

What finally clued me in was using this very handy tool - https://github.com/ChristopherSchultz/ssltest

If I specified paths to the key stores using command line args, everything worked. But using `JAVA_OPTS` didn't. *However*, once I passed the `-D` arguments on the command line everything worked as expected. You can see the same thing here - https://github.com/lukebakken/rabbitmq-users-CzgiqOUso2k/blob/main/consumer/Dockerfile#L8

We could either make PerfTest read and parse the `JAVA_OPTS` env var if it's set, or I could amend the examples to show how to correctly use the `-D` JVM arguments.

**Comment by acogoluegnes** [comment]
Yes, there's something wrong there, `JAVA_OPTS` is an environment variable that Tomcat uses, I don't know why we ended up mentioning it here, maybe because the [initial issue](https://github.com/rabbitmq/rabbitmq-perf-test/issues/35) was related to the usage of PerfTest in a web container. I'll change the documentation.

**Comment by lukebakken** [comment]
Thanks @acogoluegnes !

**Comment by acogoluegnes** [comment]
BTW, you can browse the dev documentation there: https://perftest-dev.rabbitmq.com/.
