### ISSUE TITLE
PerfTestMulti: Add benchmark specification parameter for quorum queues

### ISSUE THREAD

**Issue by eibbojtir** [rabbitmq/rabbitmq-perf-test#448]
PerfTestMulti only creates classic queues and there doesn't seem to be a benchmark scenario parameter to use quorum queues. This would be a fantastic feature addition!

**Comment by michaelklishin** [comment]
There are three options:

 * Set `x-queue-type` to `quorum`
 * Set default queue type for the virtual host (latest `3.11.x`)
 * Use `--predeclared`

**Comment by michaelklishin** [comment]
In fact, there is a `--quorum-queue` flag that sets `x-queue-type` argument for you, since 2021 https://github.com/rabbitmq/rabbitmq-perf-test/commit/291eaf649a6f14c3a68547ea3688073ea6942656.

**Comment by acogoluegnes** [comment]
It's for PerfTestMulti, which does not support this yet. I'll push a change to support it.

**Comment by acogoluegnes** [comment]
@eibbojtir I pushed a change to support quorum queues in PerfTestMulti. You can try [the latest snapshot](https://github.com/rabbitmq/rabbitmq-java-tools-binaries-dev/releases/tag/v-rabbitmq-perf-test-latest). Please use [the uber JAR](https://github.com/rabbitmq/rabbitmq-perf-test/blob/main/html/README.md#running-benchmarks) as documented, because the archives are deprecated. I documented [the usage of quorum queues](https://github.com/rabbitmq/rabbitmq-perf-test/blob/main/html/README.md#using-quorum-queues).
