### ISSUE TITLE
Concurrent test failures

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-perf-test#87]
See #84 for the discussion.

**Comment by acogoluegnes** [comment]
Tests have undergone small improvements here and there for the last few months and they seem stable now, at least on some environments where they would behave erratically before (the 3 failures are due to an error in the build configuration, not to test instability):

![screenshot from 2018-12-17 09-40-45](https://user-images.githubusercontent.com/514737/50075754-0d5cd300-01e0-11e9-82ef-9eaa6245a34a.png)

Closing for now.
